version: "3.8"
services:
  db:
    build: ./DockerFiles/Database/
    volumes:
      - ./DockerFiles/Database/:/docker-entrypoint-initdb.d
    networks:
      - webnet
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: test_swe
      MYSQL_USER: db_user
      MYSQL_PASSWORD: root
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 5s
            retries: 10
  express:
    build: ./DockerFiles/Express/
    networks:
      - webnet
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
  web:
    build: ./DockerFiles/Node/
    networks:
      - webnet
    ports:
      - "5173:5173"
    restart: on-failure
    depends_on:
      - db
      - express
networks:
  webnet:
    driver: bridge